class AppNavigationMap {
  /// Maps logical page names to your Flutter route strings.
  static const Map<String, String> routes = {
    'home': '/',
    'cart': '/cart',
    'wishlist': '/wishlist',
    'support': '/help-center',
    'notifications': '/notifications',
    'account': '/account',
    'settings': '/profile-settings',
    'orders': '/my-orders',
  };

  /// Defines natural language keywords that trigger specific routes.
  static const Map<String, List<String>> keywords = {
    'home': ['home', 'homepage', 'start', 'main page', 'go back', 'back to home'],
    'account': [
      'account',
      'my account',
      'profile',
      'my profile',
      'me',
      'personal details',
      'my info',
      'user profile',
    ],
    'settings': [
      'settings',
      'profile settings',
      'edit profile',
      'change password',
      'password',
      'privacy',
      'preferences',
      'theme',
      'dark mode',
    ],
    'cart': [
      'cart',
      'my cart',
      'basket',
      'bag',
      'shopping bag',
      'checkout',
      'pay',
    ],
    'wishlist': [
      'wishlist',
      'saved',
      'saved items',
      'favorites',
      'favourites',
      'likes',
      'bookmarks',
    ],
    'orders': [
      'orders',
      'my orders',
      'purchases',
      'my purchases',
      'order history',
      'history',
      'shipping',
      'track',
      'tracking',
      'package',
      'deliveries',
    ],
    'notifications': [
      'notifications',
      'alerts',
      'updates',
      'messages',
    ],
    'support': [
      'help',
      'support',
      'contact',
      'customer service',
      'agent',
      'problem',
      'issue',
      'refund',
      'returns',
    ],
  };
}