class AppNavigationMap {
  /// Maps logical page names to your Flutter route strings.
  static const Map<String, String> routes = {
    'home': '/',
    'cart': '/cart',
    'wishlist': '/wishlist',
    'support': '/help-center',
    'notifications': '/notifications',
    'account': '/account',
    'settings': '/profile-settings',
    'orders': '/my-orders',
    'about': '/about',
    'contact': '/contact',
    'terms': '/terms-of-service',
    'privacy': '/privacy-policy',
    'returns': '/returns',
    'sell': '/create-listing',
    'listings': '/my-listings',
    'sold': '/sold-items',
    'offers': '/my-offers',
    'reviews': '/my-reviews',
    'search': '/search',
  };

  /// Defines natural language keywords that trigger specific routes.
  static const Map<String, List<String>> keywords = {
    'home': ['home', 'homepage', 'start', 'main page', 'go back', 'back to home'],
    'account': [
      'account',
      'my account',
      'profile',
      'my profile',
      'personal details',
      'my info',
      'user profile',
    ],
    'settings': [
      'settings',
      'profile settings',
      'edit profile',
      'change password',
      'password',
      'privacy',
      'preferences',
      'theme',
      'dark mode',
    ],
    'cart': [
      'cart',
      'my cart',
      'basket',
      'bag',
      'shopping bag',
      'checkout',
      'pay',
    ],
    'wishlist': [
      'wishlist',
      'saved',
      'saved items',
      'favorites',
      'favourites',
      'likes',
      'bookmarks',
    ],
    'orders': [
      'orders',
      'my orders',
      'purchases',
      'my purchases',
      'order history',
      'history',
      'shipping',
      'track',
      'tracking',
      'package',
      'deliveries',
    ],
    'notifications': [
      'notifications',
      'alerts',
      'updates',
      'messages',
    ],
    'support': [
      'help',
      'support',
      'help center',
      'customer service',
      'agent',
    ],
    'about': [
      'about',
      'about us',
      'who are you',
      'what is thryft',
      'company info',
    ],
    'contact': [
      'contact',
      'contact us',
      'get in touch',
      'email us',
      'reach out',
    ],
    'terms': [
      'terms',
      'terms of service',
      'terms and conditions',
      'tos',
      'legal',
      'rules',
    ],
    'privacy': [
      'privacy policy',
      'privacy',
      'data policy',
      'data protection',
      'gdpr',
    ],
    'returns': [
      'returns',
      'return policy',
      'return an item',
      'send back',
      'refund',
      'money back',
    ],
    'sell': [
      'sell',
      'create listing',
      'list item',
      'new listing',
      'post item',
      'list something',
      'put up for sale',
    ],
    'listings': [
      'my listings',
      'my items',
      'my products',
      'what im selling',
      'active listings',
    ],
    'sold': [
      'sold items',
      'sold',
      'items sold',
      'completed sales',
      'past sales',
    ],
    'offers': [
      'offers',
      'my offers',
      'offers made',
      'bids',
      'negotiations',
    ],
    'reviews': [
      'reviews',
      'my reviews',
      'feedback',
      'ratings',
      'testimonials',
    ],
    'search': [
      'search',
      'browse',
      'find items',
      'shop',
      'look for',
    ],
  };

  /// Known product categories for category-browsing intent.
  static const List<String> categories = [
    'tops',
    'bottoms',
    'dresses',
    'outerwear',
    'footwear',
    'accessories',
    'activewear',
    'formal',
    'casual',
    'vintage',
    'designer',
    'streetwear',
  ];
}